@echo off
set "ARCHANGEL_ROOT=D:\1_ARCHANGEL"
set "ARCHANGEL_PYTHON_EXE=%ARCHANGEL_ROOT%\_PYTHON\Python314\python.exe"
set "CUPY_CACHE_DIR=%ARCHANGEL_ROOT%\_CACHE\cupy_kernel_cache"
set "NUMBA_CACHE_DIR=%ARCHANGEL_ROOT%\_CACHE\numba_cache"
set "PATH=%ARCHANGEL_ROOT%\_PYTHON\Python314\Scripts;%PATH%"
set "PYTHONUTF8=1"
set "PYTHONPATH=%ARCHANGEL_ROOT%\0_REGRAS_MANDATO"
cd /d "%ARCHANGEL_ROOT%"
"%ARCHANGEL_PYTHON_EXE%" "%ARCHANGEL_ROOT%\0_REGRAS_MANDATO\00_RUN_ALL.py" %*
